[package]
name = "my_programming_language"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.6", features = ["derive"] }
itertools = "0.10.3"
miette = { version = "5.0.0", features = ["fancy"] }
thiserror = "1.0.31"
